

CREATE OR REPLACE NONEDITIONABLE FUNCTION "DAW1"."CALCULAR_IMPORTE_PEDIDO"(
    P_CODIGO_PEDIDO IN CHAR
    
) RETURN NUMBER IS
    V_CANTIDAD PEDIDOS.CANTIDAD%TYPE;
    V_PRECIO PRODUCTOS_RECYCLON.PRECIO%TYPE;
    V_IDPRODUCTO PEDIDOS.IDPRODUCTO%TYPE;
    V_IMPORTE NUMBER(10,2);
    
BEGIN
    /*OBETENEMOS LOS DATOS DEL PEDIDO*/
    SELECT CANTIDAD, IDPRODUCTO INTO v_cantidad, v_idproducto
    FROM PEDIDOS
    WHERE CODIGO_PEDIDO = p_codigo_pedido;

    /*OBTENEMOS EL PRECIO DEL PRODUCTO*/
    SELECT PRECIO INTO v_precio
    FROM PRODUCTOS_RECYCLON
    WHERE IDPRODUCTO = v_idproducto;

    /*CALCULAMOS EL IMPORTE*/
    V_IMPORTE := V_CANTIDAD * V_PRECIO;

    RETURN V_IMPORTE;
    
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN NULL;
    WHEN OTHERS THEN
        RETURN NULL;
END;
/