/*PROCEDIMIENTOS MOSTRAR DATOS USUARIO*/


CREATE OR REPLACE PROCEDURE MOSTRAR_DATOS_USUARIO (
    P_ID_USUARIO IN CHAR,
    P_NOMBRE OUT VARCHAR2,
    P_APELLIDO OUT VARCHAR2,
    P_EMAIL OUT VARCHAR2,
    P_DIRECCION OUT VARCHAR2,
    P_CP OUT CHAR,
    P_FECHA_CREACION OUT DATE,
    P_TELEFONO OUT CHAR
) IS
BEGIN
    SELECT NOMBRE, APELLIDO, EMAIL, DIRECCION, CP, FECHA_CREACION, TELEFONO
    INTO P_NOMBRE, P_APELLIDO, P_EMAIL, P_DIRECCION, P_CP, P_FECHA_CREACION, P_TELEFONO
    FROM USUARIOS
    WHERE ID_USUARIO = P_ID_USUARIO;
    
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        P_NOMBRE := NULL;
        P_APELLIDO := NULL;
        P_EMAIL := NULL;
        P_DIRECCION := NULL;
        P_CP := NULL;
        P_FECHA_CREACION := NULL;
        P_TELEFONO := NULL;
    WHEN OTHER THEN
        DBMS_OUTPUT.PUT_LINE('Estas introduciendo un usuario que no existe, vuelve a intentarlo');
END;

