/*CREACION TABLAS RECYCLON*/

CREATE TABLE ADMINISTRADORES(
ID_ADMINISTRADOR CHAR(4) CONSTRAINT PK_ID_ADMINISTRADOR PRIMARY KEY,
NOMBRE VARCHAR2(15),
APELLIDO VARCHAR2 (20),
EMAIL VARCHAR2(30) UNIQUE NOT NULL,
DIRECCION VARCHAR2 (30),
CP CHAR(5)  CHECK (CP BETWEEN 48001 AND 48999),
FECHA_CREACION DATE,
TELEFONO CHAR(9)
);


CREATE TABLE USUARIOS(
ID_USUARIO CHAR(4) CONSTRAINT PK_ID_USUARIO PRIMARY KEY,
NOMBRE VARCHAR2(15),
APELLIDO VARCHAR2 (20),
EMAIL VARCHAR2(30) UNIQUE NOT NULL,
DIRECCION VARCHAR2 (30),
CP CHAR(5)  CHECK (CP BETWEEN 48001 AND 48999),
FECHA_CREACION DATE,
TELEFONO CHAR(9)
);


CREATE TABLE PRODUCTOS_RECYCLON(
IDPRODUCTO CHAR(5)CONSTRAINT PK_ID_PRODUCTOS PRIMARY KEY,
NOMBRE VARCHAR2(200),
DESCRIPCION VARCHAR (200),
TIPO_MATERIAL VARCHAR2 (30), 
PRECIO NUMBER (3,2)
);

drop table PRODUCTOS_RECYCLON;
SELECT * FROM PRODUCTOS_RECYCLON;


/*productos de prueba*/
INSERT INTO PRODUCTOS_RECYCLON VALUES('00001','Bandeja Fija','Soporte estático para organizar documentos y papeles en el escritorio','Material de escritorio',5.20);

INSERT INTO PRODUCTOS_RECYCLON VALUES('00002','AIRE ACONDICIONADO FIJO
                                    AIRE PLUS 3X1 AIRE (W015)','Aire acondicionado fijo 3 en 1, ideal para enfriar, ventilar y deshumidificar espacios'
                                    ,'Material de escritorio',821.61);
















