/*CREACION TABLAS RECYCLON*/


CREATE TABLE ADMINISTRADORES (
    ID_ADMINISTRADOR CHAR(4) CONSTRAINT PK_ID_ADMINISTRADOR PRIMARY KEY,
    NOMBRE VARCHAR2(15) NOT NULL,
    APELLIDO VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(30) UNIQUE NOT NULL,
    DIRECCION VARCHAR2(30),
    CP CHAR(5),
    FECHA_CREACION DATE DEFAULT SYSDATE,//sino pone fecha de creación será automaticamente la fecha de hoy
    TELEFONO CHAR(9),
    CONSTRAINT CHK_CP_ADMIN CHECK (TO_NUMBER(CP) BETWEEN 48001 AND 48999)//comprobar que el cp es bueno
);


CREATE TABLE USUARIOS (
    ID_USUARIO CHAR(4) CONSTRAINT PK_ID_USUARIO PRIMARY KEY,
    NOMBRE VARCHAR2(15) NOT NULL,
    APELLIDO VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(30) UNIQUE NOT NULL,
    DIRECCION VARCHAR2(30),
    CP CHAR(5),
    FECHA_CREACION DATE DEFAULT SYSDATE,
    TELEFONO CHAR(9),
    CONSTRAINT CHK_CP_USUARIO CHECK (TO_NUMBER(CP) BETWEEN 48001 AND 48999)
);


CREATE TABLE PRODUCTOS_RECYCLON (
    IDPRODUCTO CHAR(5) CONSTRAINT PK_ID_PRODUCTOS PRIMARY KEY,
    NOMBRE VARCHAR2(200) NOT NULL,
    DESCRIPCION VARCHAR2(300),
    TIPO_MATERIAL VARCHAR2(40),
    PRECIO NUMBER(5,2) CHECK (PRECIO >= 0)
);


CREATE TABLE PEDIDOS (
    CODIGO_PEDIDO CHAR(5),
    IDCOMPRADOR CHAR(4) NOT NULL,
    IDPRODUCTO CHAR(5) NOT NULL,
    CANTIDAD NUMBER(2) CHECK (CANTIDAD > 0),
    FENVIO DATE,
    CONSTRAINT PK_PEDIDOS PRIMARY KEY (CODIGO_PEDIDO),
    CONSTRAINT FK_COMPRADOR FOREIGN KEY (IDCOMPRADOR) REFERENCES USUARIOS(ID_USUARIO),
    CONSTRAINT FK_PRODUCTO FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTOS_RECYCLON(IDPRODUCTO)
);



/*productos de prueba*/
INSERT INTO PRODUCTOS_RECYCLON VALUES('00001','Bandeja Fija','Soporte estático para organizar documentos y papeles en el escritorio','Material de escritorio',5.20);

INSERT INTO PRODUCTOS_RECYCLON VALUES('00002','AIRE ACONDICIONADO FIJO
                                    AIRE PLUS 3X1 AIRE (W015)','Aire acondicionado fijo 3 en 1, ideal para enfriar, ventilar y deshumidificar espacios'
                                    ,'Material de escritorio',821.61);
















