/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.zabalburu.daw1.proyecto_recyclon_java.views;

import java.awt.event.ActionEvent;
import java.text.DateFormat;
import java.text.NumberFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import org.zabalburu.daw1.proyecto_recyclon_java.dao.DAO;
import org.zabalburu.daw1.proyecto_recyclon_java.modelo.Usuarios;

/**
 *
 * @author DAW1
 */
//NO EJECUTA POR FALTA DE DATOS EN LA BD
public class Vista_Administrador_Usuarios_1 extends javax.swing.JFrame {
    private static final int CONSULTA = 1;
    private static final int MODIFICACION = 2;
    private static final int NEW = 3;
    
    private int estado = CONSULTA;
    
    private DateFormat df = DateFormat.getDateInstance();
    
    private DAO dao = new DAO();
    
    private NumberFormat nf = NumberFormat.getCurrencyInstance();
    
    private List<Usuarios> usuario;
    
    /**
     * Creates new form Vista_administrador
     */
    public Vista_Administrador_Usuarios_1() {
        initComponents();
        cargarUsuarios();
        mostrar();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlTitulo = new javax.swing.JPanel();
        LblTitulo = new javax.swing.JLabel();
        BtnModificarProductos = new javax.swing.JButton();
        PnlDatos = new javax.swing.JPanel();
        LblProducto = new javax.swing.JLabel();
        CbxUsuarios = new javax.swing.JComboBox<>();
        LblIdProducto = new javax.swing.JLabel();
        TxtId = new javax.swing.JTextField();
        LblEmail = new javax.swing.JLabel();
        TxtEmail = new javax.swing.JTextField();
        LblNombre = new javax.swing.JLabel();
        TxtNombre = new javax.swing.JTextField();
        LblApellido = new javax.swing.JLabel();
        TxtApellido = new javax.swing.JTextField();
        LblDireccion = new javax.swing.JLabel();
        TxtDireccion = new javax.swing.JTextField();
        LblCP = new javax.swing.JLabel();
        TxtCP = new javax.swing.JTextField();
        LblTelefono = new javax.swing.JLabel();
        TxtTelefono = new javax.swing.JTextField();
        LblFechaCreacion = new javax.swing.JLabel();
        txtFecha = new javax.swing.JFormattedTextField();
        PnlBotones = new javax.swing.JPanel();
        BtnAñadirProducto = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        BtnModificar = new javax.swing.JButton();
        BtnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LblTitulo.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        LblTitulo.setText("Administrador");

        BtnModificarProductos.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        BtnModificarProductos.setText("Modificar Productos");
        BtnModificarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarProductosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlTituloLayout = new javax.swing.GroupLayout(PnlTitulo);
        PnlTitulo.setLayout(PnlTituloLayout);
        PnlTituloLayout.setHorizontalGroup(
            PnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlTituloLayout.createSequentialGroup()
                .addContainerGap(282, Short.MAX_VALUE)
                .addComponent(LblTitulo)
                .addGap(85, 85, 85)
                .addComponent(BtnModificarProductos)
                .addGap(38, 38, 38))
        );
        PnlTituloLayout.setVerticalGroup(
            PnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlTituloLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(PnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnModificarProductos)
                    .addComponent(LblTitulo))
                .addGap(17, 17, 17))
        );

        LblProducto.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        LblProducto.setText("Usuario");

        CbxUsuarios.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        CbxUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxUsuariosActionPerformed(evt);
            }
        });

        LblIdProducto.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        LblIdProducto.setText("Id Usuario");

        TxtId.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        TxtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIdActionPerformed(evt);
            }
        });

        LblEmail.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        LblEmail.setText("Email");

        TxtEmail.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        TxtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtEmailActionPerformed(evt);
            }
        });

        LblNombre.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        LblNombre.setText("Nombre");

        TxtNombre.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        TxtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombreActionPerformed(evt);
            }
        });

        LblApellido.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        LblApellido.setText("Apellido");

        TxtApellido.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        TxtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtApellidoActionPerformed(evt);
            }
        });

        LblDireccion.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        LblDireccion.setText("Direccion");

        TxtDireccion.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        TxtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDireccionActionPerformed(evt);
            }
        });

        LblCP.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        LblCP.setText("CP");

        TxtCP.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        TxtCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCPActionPerformed(evt);
            }
        });

        LblTelefono.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        LblTelefono.setText("Telefono");

        TxtTelefono.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        TxtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTelefonoActionPerformed(evt);
            }
        });

        LblFechaCreacion.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        LblFechaCreacion.setText("Fecha creacion");

        txtFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        txtFecha.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlDatosLayout = new javax.swing.GroupLayout(PnlDatos);
        PnlDatos.setLayout(PnlDatosLayout);
        PnlDatosLayout.setHorizontalGroup(
            PnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlDatosLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(PnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlDatosLayout.createSequentialGroup()
                        .addGroup(PnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblProducto)
                            .addComponent(LblIdProducto)
                            .addComponent(LblNombre))
                        .addGap(45, 45, 45)
                        .addGroup(PnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CbxUsuarios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(PnlDatosLayout.createSequentialGroup()
                                .addGroup(PnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PnlDatosLayout.createSequentialGroup()
                                        .addGroup(PnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(TxtDireccion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                            .addComponent(TxtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(PnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LblApellido)
                                            .addComponent(LblCP)
                                            .addComponent(LblTelefono)))
                                    .addGroup(PnlDatosLayout.createSequentialGroup()
                                        .addComponent(TxtId, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(LblEmail)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                    .addComponent(TxtApellido)
                                    .addComponent(TxtCP)
                                    .addComponent(TxtTelefono))))
                        .addGap(60, 60, 60))
                    .addGroup(PnlDatosLayout.createSequentialGroup()
                        .addGroup(PnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblDireccion)
                            .addComponent(LblFechaCreacion))
                        .addContainerGap(617, Short.MAX_VALUE))))
        );
        PnlDatosLayout.setVerticalGroup(
            PnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlDatosLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(PnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblProducto)
                    .addComponent(CbxUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(PnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblIdProducto)
                    .addComponent(TxtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblEmail)
                    .addComponent(TxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(PnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblApellido)
                    .addComponent(TxtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(PnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblDireccion)
                    .addComponent(TxtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblCP)
                    .addComponent(TxtCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(PnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblFechaCreacion)
                    .addComponent(LblTelefono)
                    .addComponent(TxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        BtnAñadirProducto.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        BtnAñadirProducto.setText("Añadir Usuarios");
        BtnAñadirProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAñadirProductoActionPerformed(evt);
            }
        });

        BtnEliminar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        BtnEliminar.setText("Eliminar Usuarios");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        BtnModificar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        BtnModificar.setText("Modificar Usuarios");
        BtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarActionPerformed(evt);
            }
        });

        BtnGuardar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        BtnGuardar.setText("Guardar Cambios");
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlBotonesLayout = new javax.swing.GroupLayout(PnlBotones);
        PnlBotones.setLayout(PnlBotonesLayout);
        PnlBotonesLayout.setHorizontalGroup(
            PnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlBotonesLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(BtnAñadirProducto)
                .addGap(28, 28, 28)
                .addComponent(BtnEliminar)
                .addGap(18, 18, 18)
                .addComponent(BtnModificar)
                .addGap(18, 18, 18)
                .addComponent(BtnGuardar)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        PnlBotonesLayout.setVerticalGroup(
            PnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlBotonesLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(PnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAñadirProducto)
                    .addComponent(BtnEliminar)
                    .addComponent(BtnModificar)
                    .addComponent(BtnGuardar))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PnlDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PnlBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIdActionPerformed

    private void TxtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtEmailActionPerformed

    private void TxtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombreActionPerformed

    private void TxtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDireccionActionPerformed

    private void BtnAñadirProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAñadirProductoActionPerformed
        estado = NEW;
        mostrar();
    }//GEN-LAST:event_BtnAñadirProductoActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        if(JOptionPane.showConfirmDialog(this, 
                "Está seguro",
                "Eliminar Usuario",
                JOptionPane.YES_NO_OPTION)
                ==
                JOptionPane.YES_OPTION){
            int id = Integer.parseInt(TxtId.getText());
            dao.eliminarUsuario(id);
                JOptionPane.showMessageDialog(this, "Usuario Eliminado");
                cargarUsuarios();
                CbxUsuarios.setSelectedItem(CbxUsuarios.getItemCount() == 1);
            }       
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void BtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarActionPerformed
        estado = MODIFICACION;
        mostrar();
    }//GEN-LAST:event_BtnModificarActionPerformed
    private void BtnModificarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarProductosActionPerformed
        Vista_administrador_productos_1 ventana = new Vista_administrador_productos_1();
        ventana.setVisible(true);
        mostrar();
    }//GEN-LAST:event_BtnModificarProductosActionPerformed

    private void CbxUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxUsuariosActionPerformed
      if(CbxUsuarios.getSelectedItem() != null){
          estado = CONSULTA;
          mostrar();
      }
    }//GEN-LAST:event_CbxUsuariosActionPerformed

    private void TxtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtApellidoActionPerformed

    private void TxtCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCPActionPerformed

    private void TxtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTelefonoActionPerformed

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        guardarUsuario(evt);
    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_Administrador_Usuarios_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_Administrador_Usuarios_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_Administrador_Usuarios_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_Administrador_Usuarios_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_Administrador_Usuarios_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAñadirProducto;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnModificar;
    private javax.swing.JButton BtnModificarProductos;
    private javax.swing.JComboBox<Usuarios> CbxUsuarios;
    private javax.swing.JLabel LblApellido;
    private javax.swing.JLabel LblCP;
    private javax.swing.JLabel LblDireccion;
    private javax.swing.JLabel LblEmail;
    private javax.swing.JLabel LblFechaCreacion;
    private javax.swing.JLabel LblIdProducto;
    private javax.swing.JLabel LblNombre;
    private javax.swing.JLabel LblProducto;
    private javax.swing.JLabel LblTelefono;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JPanel PnlBotones;
    private javax.swing.JPanel PnlDatos;
    private javax.swing.JPanel PnlTitulo;
    private javax.swing.JTextField TxtApellido;
    private javax.swing.JTextField TxtCP;
    private javax.swing.JTextField TxtDireccion;
    private javax.swing.JTextField TxtEmail;
    private javax.swing.JTextField TxtId;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtTelefono;
    private javax.swing.JFormattedTextField txtFecha;
    // End of variables declaration//GEN-END:variables

    private void cargarUsuarios(){
        CbxUsuarios.removeAllItems();
        List<Usuarios> usuario = dao.getUsuarios();
        for(Usuarios u: usuario){
            CbxUsuarios.addItem(u);
        }
    }
    
    private void mostrar(){
        Usuarios seleccionado = (Usuarios) CbxUsuarios.getSelectedItem();
        if(estado == NEW){
            TxtId.setText("");
            TxtApellido.setText("");
            TxtCP.setText("");
            TxtDireccion.setText("");
            TxtEmail.setText("");
            TxtNombre.setText("");
            TxtTelefono.setText("");
            txtFecha.setValue(new Date());
                    
        }
        if(estado != NEW){
        TxtId.setText(String.valueOf(seleccionado.getId_Usuario()));
        TxtNombre.setText((seleccionado.getNombre()));
        TxtApellido.setText(seleccionado.getApellido());
        TxtCP.setText(seleccionado.getCP());
        TxtDireccion.setText(seleccionado.getDireccion());
        txtFecha.setValue(seleccionado.getFecha_Creacion());
        TxtTelefono.setText(String.valueOf(seleccionado.getTelefono()));
        TxtEmail.setText(String.valueOf(seleccionado.getEmail()));
        }
        TxtApellido.setEditable(estado != CONSULTA);
        TxtNombre.setEditable(estado != CONSULTA);
        TxtCP.setEditable(estado != CONSULTA);
        TxtDireccion.setEditable(estado != CONSULTA);
        txtFecha.setEditable(estado != CONSULTA);
        TxtTelefono.setEditable(estado != CONSULTA);
        TxtEmail.setEditable(estado != CONSULTA);
        TxtId.setEnabled(false);
        BtnGuardar.setEnabled(estado != CONSULTA);
        BtnAñadirProducto.setEnabled(estado != MODIFICACION);
        BtnModificar.setEnabled(estado != MODIFICACION);
        BtnEliminar.setEnabled(estado != MODIFICACION);
    }
    private void guardarUsuario(ActionEvent evt){
        Usuarios u = new Usuarios();
        u.setNombre(TxtNombre.getText());
        u.setTelefono(TxtTelefono.getText());
        u.setCP(TxtCP.getText());
        u.setApellido(TxtApellido.getText());
        u.setEmail(TxtEmail.getText());
        u.setDireccion(TxtDireccion.getText());
        Date fecha = (Date) txtFecha.getValue();
        u.setFecha_Creacion(fecha);
        if(estado == MODIFICACION){
        //u.setId_Usuario(Integer.parseInt(TxtFecha.getText()));
        dao.modificarUsuario(u);
        }else if(estado == NEW){
            dao.nuevoUsuario(u);
            cargarUsuarios();
            CbxUsuarios.setSelectedItem(CbxUsuarios.getItemCount()-1);
        }
        estado = CONSULTA;
        mostrar();
    }
}
