/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.zabalburu.daw1.proyecto_recyclon_java.views;

import java.awt.event.ActionEvent;
import java.text.NumberFormat;
import java.util.List;
import javax.swing.JOptionPane;
import org.zabalburu.daw1.proyecto_recyclon_java.dao.DAO;
import org.zabalburu.daw1.proyecto_recyclon_java.modelo.Productos_Recyclon;

/**
 *
 * @author DAW1
 */
public class Vista_administrador_productos_1 extends javax.swing.JFrame {
     private static final int CONSULTA = 1;
    private static final int MODIFICACION = 2;
    private static final int NEW = 3;
    
    private int estado = CONSULTA;
    
    private List<Productos_Recyclon> productos;
    
    private DAO dao = new DAO();
    private NumberFormat nf = NumberFormat.getCurrencyInstance();
    /**
     * Creates new form Vista_administrador
     */
    public Vista_administrador_productos_1() {
        initComponents();
        cargarProducto();
        mostrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        PnlTitulo = new javax.swing.JPanel();
        LblTitulo = new javax.swing.JLabel();
        BtnModificarUsuarios = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        PnlDatos = new javax.swing.JPanel();
        LblProducto = new javax.swing.JLabel();
        CbxProducto = new javax.swing.JComboBox<>();
        LblIdProducto = new javax.swing.JLabel();
        TxtId = new javax.swing.JTextField();
        LblPrecio = new javax.swing.JLabel();
        LblNombre = new javax.swing.JLabel();
        TxtNombre = new javax.swing.JTextField();
        LblTipoMaterial = new javax.swing.JLabel();
        TxtTipoMaterial = new javax.swing.JTextField();
        LblDescripcion = new javax.swing.JLabel();
        TxtDescripcion = new javax.swing.JTextField();
        ftxPrecio = new javax.swing.JFormattedTextField();
        PnlBotones = new javax.swing.JPanel();
        BtnAñadirProducto = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        BtnModificar = new javax.swing.JButton();
        BtnGuardar = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        jTextField5.setText("jTextField5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LblTitulo.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        LblTitulo.setText("Administrador");

        BtnModificarUsuarios.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        BtnModificarUsuarios.setText("Modificar Usuarios");
        BtnModificarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarUsuariosActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/zabalburu/daw1/proyecto_recyclon_java/icon/Captura de pantalla 2025-05-15 134420.png"))); // NOI18N

        javax.swing.GroupLayout PnlTituloLayout = new javax.swing.GroupLayout(PnlTitulo);
        PnlTitulo.setLayout(PnlTituloLayout);
        PnlTituloLayout.setHorizontalGroup(
            PnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlTituloLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LblTitulo)
                .addGap(72, 72, 72)
                .addComponent(BtnModificarUsuarios)
                .addGap(53, 53, 53))
        );
        PnlTituloLayout.setVerticalGroup(
            PnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlTituloLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(PnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(BtnModificarUsuarios)
                    .addComponent(LblTitulo))
                .addContainerGap())
        );

        LblProducto.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        LblProducto.setText("Producto");

        CbxProducto.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        CbxProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxProductoActionPerformed(evt);
            }
        });

        LblIdProducto.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        LblIdProducto.setText("Id Producto");

        TxtId.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        TxtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIdActionPerformed(evt);
            }
        });

        LblPrecio.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        LblPrecio.setText("Precio");

        LblNombre.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        LblNombre.setText("Nombre");

        TxtNombre.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        TxtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombreActionPerformed(evt);
            }
        });

        LblTipoMaterial.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        LblTipoMaterial.setText("Tipo de material");

        TxtTipoMaterial.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        LblDescripcion.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        LblDescripcion.setText("Descripcion");

        TxtDescripcion.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        TxtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDescripcionActionPerformed(evt);
            }
        });

        ftxPrecio.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        ftxPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftxPrecioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlDatosLayout = new javax.swing.GroupLayout(PnlDatos);
        PnlDatos.setLayout(PnlDatosLayout);
        PnlDatosLayout.setHorizontalGroup(
            PnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlDatosLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(PnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlDatosLayout.createSequentialGroup()
                        .addComponent(LblDescripcion)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PnlDatosLayout.createSequentialGroup()
                        .addGroup(PnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblProducto)
                            .addComponent(LblIdProducto)
                            .addComponent(LblNombre))
                        .addGap(45, 45, 45)
                        .addGroup(PnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtDescripcion)
                            .addComponent(CbxProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(PnlDatosLayout.createSequentialGroup()
                                .addGroup(PnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PnlDatosLayout.createSequentialGroup()
                                        .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(LblTipoMaterial))
                                    .addGroup(PnlDatosLayout.createSequentialGroup()
                                        .addComponent(TxtId, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(LblPrecio)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtTipoMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                    .addComponent(ftxPrecio))))
                        .addGap(60, 60, 60))))
        );
        PnlDatosLayout.setVerticalGroup(
            PnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlDatosLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(PnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblProducto)
                    .addComponent(CbxProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(PnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblIdProducto)
                    .addComponent(TxtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblPrecio)
                    .addComponent(ftxPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(PnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblTipoMaterial)
                    .addComponent(TxtTipoMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(PnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblDescripcion)
                    .addComponent(TxtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        BtnAñadirProducto.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        BtnAñadirProducto.setText("Añadir Producto");
        BtnAñadirProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAñadirProductoActionPerformed(evt);
            }
        });

        BtnEliminar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        BtnEliminar.setText("Eliminar Producto");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        BtnModificar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        BtnModificar.setText("Modificar Producto");
        BtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarActionPerformed(evt);
            }
        });

        BtnGuardar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        BtnGuardar.setText("Guardar Cambios");
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlBotonesLayout = new javax.swing.GroupLayout(PnlBotones);
        PnlBotones.setLayout(PnlBotonesLayout);
        PnlBotonesLayout.setHorizontalGroup(
            PnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlBotonesLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(BtnAñadirProducto)
                .addGap(28, 28, 28)
                .addComponent(BtnEliminar)
                .addGap(18, 18, 18)
                .addComponent(BtnModificar)
                .addGap(18, 18, 18)
                .addComponent(BtnGuardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PnlBotonesLayout.setVerticalGroup(
            PnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlBotonesLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(PnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAñadirProducto)
                    .addComponent(BtnEliminar)
                    .addComponent(BtnModificar)
                    .addComponent(BtnGuardar))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PnlDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PnlBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIdActionPerformed

    private void TxtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombreActionPerformed

    private void TxtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDescripcionActionPerformed

    private void BtnAñadirProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAñadirProductoActionPerformed
        estado = NEW;
        mostrar();
    }//GEN-LAST:event_BtnAñadirProductoActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        if(JOptionPane.showConfirmDialog(this, 
                "Está seguro",
                "Eliminar Producto",
                JOptionPane.YES_NO_OPTION)
                ==
                JOptionPane.YES_OPTION){
            int id = Integer.parseInt(TxtId.getText());
            if(dao.eliminarProducto(id)){
                JOptionPane.showMessageDialog(this, "Producto Eliminado");
                productos = dao.getProductos();
                cargarProducto();
                CbxProducto.setSelectedItem(CbxProducto.getItemCount() == 1);
            }
            }
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void BtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarActionPerformed
        estado = MODIFICACION;
        mostrar();
    }//GEN-LAST:event_BtnModificarActionPerformed

    private void BtnModificarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarUsuariosActionPerformed
        Vista_Administrador_Usuarios_1 ventana = new Vista_Administrador_Usuarios_1();
        ventana.setVisible(true);
    }//GEN-LAST:event_BtnModificarUsuariosActionPerformed

    private void CbxProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxProductoActionPerformed
        if (CbxProducto.getSelectedItem() != null){
            estado = CONSULTA;
            mostrar();
        }
    }//GEN-LAST:event_CbxProductoActionPerformed

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        GuardarProducto(evt);     
    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void ftxPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftxPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftxPrecioActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_administrador_productos_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_administrador_productos_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_administrador_productos_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_administrador_productos_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_administrador_productos_1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAñadirProducto;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnModificar;
    private javax.swing.JButton BtnModificarUsuarios;
    private javax.swing.JComboBox<Productos_Recyclon> CbxProducto;
    private javax.swing.JLabel LblDescripcion;
    private javax.swing.JLabel LblIdProducto;
    private javax.swing.JLabel LblNombre;
    private javax.swing.JLabel LblPrecio;
    private javax.swing.JLabel LblProducto;
    private javax.swing.JLabel LblTipoMaterial;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JPanel PnlBotones;
    private javax.swing.JPanel PnlDatos;
    private javax.swing.JPanel PnlTitulo;
    private javax.swing.JTextField TxtDescripcion;
    private javax.swing.JTextField TxtId;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtTipoMaterial;
    private javax.swing.JFormattedTextField ftxPrecio;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables

    private void mostrar() {
        Productos_Recyclon pro = (Productos_Recyclon) CbxProducto.getSelectedItem();
        if(estado == NEW){
            TxtId.setText("");
            TxtDescripcion.setText("");
            TxtNombre.setText("");
            TxtTipoMaterial.setText("");
            ftxPrecio.setText("");   
        }
        if(estado != NEW){
        TxtId.setText(String.valueOf(pro.getIdProducto()));
        ftxPrecio.setText(String.valueOf(nf.format(pro.getPrecio())));
        TxtNombre.setText(String.valueOf(pro.getNombre()));
        TxtTipoMaterial.setText(String.valueOf(pro.getTipo_Material()));
        TxtDescripcion.setText(String.valueOf(pro.getDescripcion()));
        }
        TxtId.setEnabled(false);
        TxtNombre.setEditable(estado != CONSULTA);
        TxtDescripcion.setEditable(estado != CONSULTA);
        TxtTipoMaterial.setEditable(estado != CONSULTA);
        ftxPrecio.setEditable(estado != CONSULTA);
        BtnGuardar.setEnabled(estado != CONSULTA);
        BtnModificar.setEnabled(estado != MODIFICACION);
        BtnAñadirProducto.setEnabled(estado != MODIFICACION);
        BtnEliminar.setEnabled(estado != MODIFICACION);   
    }

    private void cargarProducto() {
        CbxProducto.removeAllItems();
        productos = dao.getProductos();
        for(Productos_Recyclon p : productos){
            CbxProducto.addItem(p);
        }
        
    }
    private void GuardarProducto(ActionEvent evt){
        Productos_Recyclon p = new Productos_Recyclon();
        p.setNombre(TxtNombre.getText());
        p.setTipo_Material(TxtTipoMaterial.getText());
        p.setDescripcion(TxtDescripcion.getText());
        p.setPrecio(Double.parseDouble(ftxPrecio.getText()));
        if(estado == MODIFICACION){
            p.setIdProducto(Integer.parseInt(TxtId.getText()));
            dao.modificarProducto(p);
        }else if(estado == NEW){
            dao.nuevoProducto(p);
            cargarProducto();
            CbxProducto.setSelectedIndex(CbxProducto.getItemCount()-1);
            
        }
        estado = CONSULTA;
        
    }
}
